language: android
sudo: false
before_install:
     - chmod +x gradlew
jdk:
  - oraclejdk8
  
android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.0
    - extra-android-support
    - extra-android-m2repository
    
script:
- ./gradlew :app:assembleRelease

notifications:
  email: false
  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
