language: android
before_install:
     - chmod +x gradlew
jdk:
  - oraclejdk8
  
android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.0
    
notifications:
  email: false
  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
