language: android
sudo: false
before_install:
     - chmod +x gradlew
jdk:
  - oraclejdk8
  
android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.0
    - extra-android-support
    - extra-android-m2repository
    
script:
- ./gradlew :app:assembleRelease

notifications:
  email: false
  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://plumsky:$GITHUB_API_KEY@github.com/plumsky/StereoView/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
  
